version: "3"
services:
  varnish:
    environment:
    - VARNISH_BACKEND_ADDRESS=host.docker.internal
    - VARNISH_BACKEND_PORT=8000
    image: thiagofigueiro/varnish-alpine-docker
    volumes:
    - ./config/varnish/default.vcl:/etc/varnish/default.vcl:ro
    ports:
    - 80:80